"""Add onboarding models

Revision ID: 4f6c81c0bb49
Revises: cf2aef5d9a26
Create Date: 2025-10-17 11:25:38.311263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6c81c0bb49'
down_revision: Union[str, Sequence[str], None] = 'cf2aef5d9a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('business_name', sa.String(length=255), nullable=False))
    op.add_column('clients', sa.Column('business_address', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('contact_person', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('clients', sa.Column('alternate_phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('services_requested', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('clients', sa.Column('onboarding_status', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('account_manager_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('terms_accepted', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('clients', sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('activation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('temp_password_sent', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('temp_password_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_client_status', table_name='clients')
    op.create_index('ix_client_account_manager', 'clients', ['account_manager_id'], unique=False)
    op.create_index('ix_client_onboarding_status', 'clients', ['onboarding_status'], unique=False)
    op.create_index(op.f('ix_clients_account_manager_id'), 'clients', ['account_manager_id'], unique=False)
    op.create_index(op.f('ix_clients_onboarding_status'), 'clients', ['onboarding_status'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['account_manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('clients', 'company_name')
    op.drop_column('clients', 'contact_phone')
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'contact_name')
    op.drop_column('clients', 'contact_email')
    op.drop_column('clients', 'payment_verified')
    op.drop_column('clients', 'kyc_uploaded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('kyc_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('payment_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('contact_email', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('contact_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('contact_phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('company_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_onboarding_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_account_manager_id'), table_name='clients')
    op.drop_index('ix_client_onboarding_status', table_name='clients')
    op.drop_index('ix_client_account_manager', table_name='clients')
    op.create_index('ix_client_status', 'clients', ['status'], unique=False)
    op.drop_column('clients', 'temp_password_sent_at')
    op.drop_column('clients', 'temp_password_sent')
    op.drop_column('clients', 'rejection_reason')
    op.drop_column('clients', 'admin_notes')
    op.drop_column('clients', 'activation_date')
    op.drop_column('clients', 'verification_date')
    op.drop_column('clients', 'registration_date')
    op.drop_column('clients', 'privacy_policy_accepted')
    op.drop_column('clients', 'terms_accepted_at')
    op.drop_column('clients', 'terms_accepted')
    op.drop_column('clients', 'account_manager_id')
    op.drop_column('clients', 'onboarding_status')
    op.drop_column('clients', 'services_requested')
    op.drop_column('clients', 'alternate_phone')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'contact_person')
    op.drop_column('clients', 'registration_number')
    op.drop_column('clients', 'business_type')
    op.drop_column('clients', 'business_address')
    op.drop_column('clients', 'business_name')
    # ### end Alembic commands ###
