"""Add onboarding models

Revision ID: 7b181dd68899
Revises: 4f6c81c0bb49
Create Date: 2025-10-17 11:27:50.314418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b181dd68899'
down_revision: Union[str, Sequence[str], None] = '4f6c81c0bb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_letters',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('services_included', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=False),
    sa.Column('fee_structure', sa.Text(), nullable=False),
    sa.Column('terms_and_conditions', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('commencement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_ip_address', sa.String(length=45), nullable=True),
    sa.Column('client_consent', sa.Integer(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_engagement_client', 'engagement_letters', ['client_id'], unique=False)
    op.create_index(op.f('ix_engagement_letters_client_id'), 'engagement_letters', ['client_id'], unique=False)
    op.create_index(op.f('ix_engagement_letters_created_at'), 'engagement_letters', ['created_at'], unique=False)
    op.create_index(op.f('ix_engagement_letters_id'), 'engagement_letters', ['id'], unique=False)
    op.create_index(op.f('ix_engagement_letters_status'), 'engagement_letters', ['status'], unique=False)
    op.create_index(op.f('ix_engagement_letters_updated_at'), 'engagement_letters', ['updated_at'], unique=False)
    op.create_index('ix_engagement_status', 'engagement_letters', ['status'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_comments', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_resubmission', sa.Integer(), nullable=False),
    sa.Column('resubmission_count', sa.Integer(), nullable=False),
    sa.Column('previous_document_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_document_id'], ['kyc_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_client', 'kyc_documents', ['client_id'], unique=False)
    op.create_index('ix_kyc_document_type', 'kyc_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_kyc_documents_client_id'), 'kyc_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_kyc_documents_created_at'), 'kyc_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_kyc_documents_document_type'), 'kyc_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_kyc_documents_id'), 'kyc_documents', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_documents_updated_at'), 'kyc_documents', ['updated_at'], unique=False)
    op.create_index(op.f('ix_kyc_documents_verification_status'), 'kyc_documents', ['verification_status'], unique=False)
    op.create_index('ix_kyc_verification_status', 'kyc_documents', ['verification_status'], unique=False)
    op.create_table('payments',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_file_path', sa.String(length=500), nullable=True),
    sa.Column('receipt_filename', sa.String(length=255), nullable=True),
    sa.Column('receipt_file_size', sa.BigInteger(), nullable=True),
    sa.Column('receipt_mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('bank_statement_matched', sa.Integer(), nullable=False),
    sa.Column('bank_statement_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_client', 'payments', ['client_id'], unique=False)
    op.create_index('ix_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_index('ix_payment_verification_status', 'payments', ['verification_status'], unique=False)
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_updated_at'), 'payments', ['updated_at'], unique=False)
    op.create_index(op.f('ix_payments_verification_status'), 'payments', ['verification_status'], unique=False)
    op.add_column('clients', sa.Column('business_name', sa.String(length=255), nullable=False))
    op.add_column('clients', sa.Column('business_address', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('contact_person', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('clients', sa.Column('alternate_phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('services_requested', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('clients', sa.Column('onboarding_status', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('account_manager_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('terms_accepted', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('clients', sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('activation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('temp_password_sent', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('temp_password_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_client_status', table_name='clients')
    op.create_index('ix_client_account_manager', 'clients', ['account_manager_id'], unique=False)
    op.create_index('ix_client_onboarding_status', 'clients', ['onboarding_status'], unique=False)
    op.create_index(op.f('ix_clients_account_manager_id'), 'clients', ['account_manager_id'], unique=False)
    op.create_index(op.f('ix_clients_onboarding_status'), 'clients', ['onboarding_status'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['account_manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('clients', 'contact_name')
    op.drop_column('clients', 'kyc_uploaded')
    op.drop_column('clients', 'contact_phone')
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'company_name')
    op.drop_column('clients', 'contact_email')
    op.drop_column('clients', 'payment_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('payment_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('contact_email', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('company_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('contact_phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('kyc_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('contact_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_onboarding_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_account_manager_id'), table_name='clients')
    op.drop_index('ix_client_onboarding_status', table_name='clients')
    op.drop_index('ix_client_account_manager', table_name='clients')
    op.create_index('ix_client_status', 'clients', ['status'], unique=False)
    op.drop_column('clients', 'temp_password_sent_at')
    op.drop_column('clients', 'temp_password_sent')
    op.drop_column('clients', 'rejection_reason')
    op.drop_column('clients', 'admin_notes')
    op.drop_column('clients', 'activation_date')
    op.drop_column('clients', 'verification_date')
    op.drop_column('clients', 'registration_date')
    op.drop_column('clients', 'privacy_policy_accepted')
    op.drop_column('clients', 'terms_accepted_at')
    op.drop_column('clients', 'terms_accepted')
    op.drop_column('clients', 'account_manager_id')
    op.drop_column('clients', 'onboarding_status')
    op.drop_column('clients', 'services_requested')
    op.drop_column('clients', 'alternate_phone')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'contact_person')
    op.drop_column('clients', 'registration_number')
    op.drop_column('clients', 'business_type')
    op.drop_column('clients', 'business_address')
    op.drop_column('clients', 'business_name')
    op.drop_index(op.f('ix_payments_verification_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_updated_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_index('ix_payment_verification_status', table_name='payments')
    op.drop_index('ix_payment_date', table_name='payments')
    op.drop_index('ix_payment_client', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_kyc_verification_status', table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_verification_status'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_updated_at'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_id'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_document_type'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_created_at'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_client_id'), table_name='kyc_documents')
    op.drop_index('ix_kyc_document_type', table_name='kyc_documents')
    op.drop_index('ix_kyc_client', table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index('ix_engagement_status', table_name='engagement_letters')
    op.drop_index(op.f('ix_engagement_letters_updated_at'), table_name='engagement_letters')
    op.drop_index(op.f('ix_engagement_letters_status'), table_name='engagement_letters')
    op.drop_index(op.f('ix_engagement_letters_id'), table_name='engagement_letters')
    op.drop_index(op.f('ix_engagement_letters_created_at'), table_name='engagement_letters')
    op.drop_index(op.f('ix_engagement_letters_client_id'), table_name='engagement_letters')
    op.drop_index('ix_engagement_client', table_name='engagement_letters')
    op.drop_table('engagement_letters')
    # ### end Alembic commands ###
